"""initial: traces and renders

Revision ID: 9e191b25d172
Revises: 
Create Date: 2026-05-08 20:29:54.474761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e191b25d172'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('short_id', sa.String(length=32), nullable=False),
    sa.Column('owner_login', sa.String(length=64), nullable=False),
    sa.Column('repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_url', sa.String(length=512), nullable=False),
    sa.Column('pr_title', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('plugin_version', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('redaction_count_client', sa.Integer(), nullable=False),
    sa.Column('redaction_count_server', sa.Integer(), nullable=False),
    sa.Column('blob_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_owner_login'), 'traces', ['owner_login'], unique=False)
    op.create_index(op.f('ix_traces_pr_number'), 'traces', ['pr_number'], unique=False)
    op.create_index(op.f('ix_traces_repo_full_name'), 'traces', ['repo_full_name'], unique=False)
    op.create_index(op.f('ix_traces_short_id'), 'traces', ['short_id'], unique=True)
    op.create_table('renders',
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('rendered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('renderer_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renders')
    op.drop_index(op.f('ix_traces_short_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_repo_full_name'), table_name='traces')
    op.drop_index(op.f('ix_traces_pr_number'), table_name='traces')
    op.drop_index(op.f('ix_traces_owner_login'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###
