#!/usr/bin/env python3
"""Generate the self-contained Cursor marketplace plugin from plugins/cli.

vibeshub ships as a shared Claude+Codex plugin at plugins/cli. Cursor's
marketplace needs a *separate*, self-contained source with no .claude-plugin/
ancestor and no Claude-format hooks (see vibeshub/vibeshub#108). Rather than
hand-maintain a duplicate, this script regenerates that tree from plugins/cli:
the single source of truth stays here.

Usage:
    python3 scripts/sync-cursor-plugin.py [--out DIR] [--source DIR] [--check]

    --out DIR     output directory (default: dist/vibeshub-cursor, gitignored).
                  May also be a checked-out clone of vibeshub/vibeshub-cursor;
                  only the generated paths are touched, never .git/.gitignore.
    --source DIR  plugin source (default: plugins/cli).
    --check       regenerate into a temp dir and diff against --out; exit 1 on
                  drift (no writes). For CI "cursor plugin is in sync" checks.

The generated tree is fully local-testable before any marketplace submission:
run hooks/on-pr-share.py standalone against a Cursor payload, or symlink the
tree into ~/.cursor/plugins/local/ and validate in the Cursor GUI.
"""
from __future__ import annotations

import argparse
import filecmp
import json
import re
import shutil
import stat
import sys
import tempfile
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_SOURCE = _REPO_ROOT / "plugins" / "cli"
_DEFAULT_OUT = _REPO_ROOT / "dist" / "vibeshub-cursor"

# Top-level runtime modules copied verbatim from the plugin source. The whole
# vibeshub_client/ package is copied separately. platform_adapter imports all
# three readers regardless of platform, so they all ship.
_TOP_MODULES = ("platform_adapter.py", "reader.py", "codex_reader.py", "cursor_reader.py")

# Everything this script owns in the output dir. Only these are removed before a
# regenerate, so pointing --out at a real clone leaves .git/.gitignore intact.
_MANAGED = (".cursor-plugin", "hooks", "vibeshub_client") + _TOP_MODULES + ("README.md", "LICENSE")

_REPOSITORY = "https://github.com/vibeshub/vibeshub-cursor"
_LICENSE_YEAR = "2026"

_PLUGIN_DESCRIPTION = (
    "Upload your Cursor agent conversation traces to vibeshub when you open or "
    "update a pull request."
)
_MARKETPLACE_DESCRIPTION = "Share and showcase your Cursor agent coding sessions on vibeshub."


def _read_version(source: Path) -> str:
    """Read PLUGIN_VERSION from the source so the Cursor plugin can never drift."""
    text = (source / "vibeshub_client" / "version.py").read_text(encoding="utf-8")
    match = re.search(r'PLUGIN_VERSION\s*=\s*["\']([^"\']+)["\']', text)
    if not match:
        raise ValueError("could not find PLUGIN_VERSION in vibeshub_client/version.py")
    return match.group(1)


def _marketplace_json() -> str:
    data = {
        "name": "vibeshub",
        "owner": {"name": "vibeshub", "email": "team@vibeshub.ai"},
        "metadata": {"description": _MARKETPLACE_DESCRIPTION},
        "plugins": [
            {
                "name": "vibeshub",
                "source": ".",
                "description": _PLUGIN_DESCRIPTION,
                "category": "Engineering",
                "keywords": ["cursor", "traces", "pull-requests", "ai-coding"],
            }
        ],
    }
    return json.dumps(data, indent=2) + "\n"


def _plugin_json(version: str) -> str:
    data = {
        "name": "vibeshub",
        "description": _PLUGIN_DESCRIPTION,
        "version": version,
        "author": {
            "name": "vibeshub",
            "email": "bhavya@vibeshub.ai",
            "url": "https://vibeshub.ai/",
        },
        "homepage": "https://vibeshub.ai/",
        "repository": _REPOSITORY,
        "license": "MIT",
        "keywords": ["cursor", "traces", "pull-requests", "ai-coding"],
        "hooks": "./hooks/hooks.json",
    }
    return json.dumps(data, indent=2) + "\n"


def _hooks_json() -> str:
    data = {
        # Required by Cursor's hooks-config validator; without it the whole
        # hooks file is silently rejected and the plugin's hooks never run.
        "version": 1,
        "hooks": {
            "afterShellExecution": [
                {
                    "command": "./hooks/on-pr-share.sh",
                    # Same trigger set as vibeshub_client.share_trigger.
                    "matcher": r"gh pr (create|edit)|git\s+push",
                }
            ]
        }
    }
    return json.dumps(data, indent=2) + "\n"


_WRAPPER = """\
#!/usr/bin/env bash
# GENERATED by scripts/sync-cursor-plugin.py in vibeshub/vibeshub (do not edit).
# Cursor afterShellExecution wrapper for vibeshub auto-share. Resolves its own
# directory (cwd-independent) so the hook works wherever Cursor runs it, and
# exports the platform so the adapter routes to the Cursor transcript reader.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
export VIBESHUB_PLATFORM=cursor
exec python3 "$here/on-pr-share.py"
"""


def _readme(version: str) -> str:
    return f"""\
# vibeshub for Cursor

Upload your **Cursor agent** conversation traces to
[vibeshub](https://vibeshub.ai/) when you open or update a pull request, so your
team can see how a change was actually built.

> **Generated (do not hand-edit).** This repository is generated from
> [`vibeshub/vibeshub`](https://github.com/vibeshub/vibeshub) by
> `scripts/sync-cursor-plugin.py`. Send changes there.

Version: {version}

## What it does

After a `gh pr create`, `gh pr edit`, or `git push`, an `afterShellExecution`
hook redacts the current Cursor agent transcript, uploads it to vibeshub, and
(for a brand-new trace) comments the trace link on the PR.

## Install (Cursor marketplace)

Install **vibeshub** from the Cursor marketplace, then reload the window.

### Requirements

- [`gh`](https://cli.github.com/) installed and authenticated (`gh auth login`)
- Python 3.9 or newer available as `python3`
- A GitHub remote and, for `git push` or `gh pr edit`, an open pull request for
  the current branch

## Local development / testing (no marketplace needed)

Cursor loads plugins straight from a directory:

```sh
ln -s "$(pwd)" ~/.cursor/plugins/local/vibeshub-cursor
```

Enable **Settings → Features → "Include third-party Plugins, Skills, and other
configs"**, then **Reload Window**. The Plugins panel should show this plugin's
Cursor description and an `afterShellExecution` hook. Trigger it with a real
`git push` to an open PR and watch the Hooks output channel.

You can also exercise the share script without Cursor at all:

```sh
echo '{{"command":"git push","cwd":"'"$(pwd)"'"}}' \\
  | VIBESHUB_PLATFORM=cursor python3 hooks/on-pr-share.py
```

## Troubleshooting hooks

If the Hooks output channel reports that `./hooks/on-pr-share.sh` cannot be
found, Cursor did not resolve the command relative to the plugin root. Edit
`hooks/hooks.json` to use an absolute path to `on-pr-share.sh`, or install the
plugin locally by symlinking this directory into
`~/.cursor/plugins/local/vibeshub-cursor` (see "Local development / testing"
above) so Cursor resolves the hook from a fixed path.

## License

MIT, see [LICENSE](./LICENSE).
"""


def _license() -> str:
    return f"""\
MIT License

Copyright (c) {_LICENSE_YEAR} vibeshub

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


def _write(path: Path, text: str, *, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    if executable:
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _clean_managed(out: Path) -> None:
    for name in _MANAGED:
        target = out / name
        if target.is_dir() and not target.is_symlink():
            shutil.rmtree(target)
        elif target.exists() or target.is_symlink():
            target.unlink()


def generate(out: Path, source: Path = _DEFAULT_SOURCE) -> Path:
    """Generate the Cursor plugin tree into `out` from plugin `source`.

    Only the managed paths are removed/written; anything else in `out` (e.g. a
    `.git` directory when `out` is a real clone) is left untouched. Returns `out`.
    """
    out = Path(out)
    source = Path(source)
    version = _read_version(source)

    out.mkdir(parents=True, exist_ok=True)
    _clean_managed(out)

    # Manifests.
    _write(out / ".cursor-plugin" / "marketplace.json", _marketplace_json())
    _write(out / ".cursor-plugin" / "plugin.json", _plugin_json(version))

    # Hooks: Cursor-format manifest, generated wrapper, copied share script.
    _write(out / "hooks" / "hooks.json", _hooks_json())
    _write(out / "hooks" / "on-pr-share.sh", _WRAPPER, executable=True)
    shutil.copy2(source / "hooks" / "on-pr-share.py", out / "hooks" / "on-pr-share.py")

    # Runtime code: the whole vibeshub_client/ package plus the top-level modules.
    shutil.copytree(
        source / "vibeshub_client",
        out / "vibeshub_client",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )
    for module in _TOP_MODULES:
        shutil.copy2(source / module, out / module)

    # Docs / license.
    _write(out / "README.md", _readme(version))
    _write(out / "LICENSE", _license())

    return out


def check(out: Path, source: Path = _DEFAULT_SOURCE) -> bool:
    """Return True if `out` matches a fresh generate (no drift), else False."""
    out = Path(out)
    with tempfile.TemporaryDirectory() as tmp:
        fresh = generate(Path(tmp) / "vibeshub-cursor", source=source)
        return _trees_equal(fresh, out)


def _trees_equal(a: Path, b: Path) -> bool:
    """Compare only the managed paths of two trees, byte-for-byte."""
    for name in _MANAGED:
        pa, pb = a / name, b / name
        if pa.is_dir():
            if not _dirs_equal(pa, pb):
                return False
        else:
            if not pb.is_file() or pa.read_bytes() != pb.read_bytes():
                return False
    return True


def _dirs_equal(a: Path, b: Path) -> bool:
    cmp = filecmp.dircmp(a, b)
    if cmp.left_only or cmp.right_only or cmp.diff_files or cmp.funny_files:
        return False
    for sub in cmp.common_dirs:
        if not _dirs_equal(a / sub, b / sub):
            return False
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the Cursor marketplace plugin from plugins/cli.")
    parser.add_argument("--out", type=Path, default=_DEFAULT_OUT, help="output directory")
    parser.add_argument("--source", type=Path, default=_DEFAULT_SOURCE, help="plugin source directory")
    parser.add_argument("--check", action="store_true", help="check --out is in sync; exit 1 on drift")
    args = parser.parse_args(argv)

    if args.check:
        if check(args.out, source=args.source):
            print(f"in sync: {args.out}")
            return 0
        print(f"OUT OF SYNC: {args.out} differs from a fresh generate", file=sys.stderr)
        return 1

    out = generate(args.out, source=args.source)
    print(f"Generated Cursor plugin at {out}")
    print("Local test: symlink into ~/.cursor/plugins/local/ then Reload Window in Cursor.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
